services:
  - type: web
    name: anime-metadata-api
    env: python
    region: singapore  # 한국에서 가장 가까운 지역
    plan: free  # 무료 플랜 (월 750시간)
    buildCommand: pip install -r requirements-api.txt
    startCommand: python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false  # Render 대시보드에서 직접 설정
      - key: NOTION_TOKEN
        sync: false  # Render 대시보드에서 직접 설정
      - key: NOTION_DATABASE_ID
        sync: false  # Render 대시보드에서 직접 설정
      - key: LAFTEL_API_KEY
        sync: false  # Render 대시보드에서 직접 설정 (필요시)
    # 자동 배포 설정
    autoDeploy: true  # main 브랜치 push시 자동 배포
    # 헬스체크 설정
    healthCheckPath: /health
